<a href="https://colab.research.google.com/github/RutuKhatal-04/Machine-Learning/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas is used for file handling
It expect to have data in tables

In [ ]:
from pandas import Series,DataFrame
import pandas as pd

In [ ]:
s1=Series(range(0,4))
s6=Series(range(1,5))

In [ ]:
s2=Series(['a','b'])
s3=Series(['c','d'])
s4=s2+s3
s7=s1+s6
print(s7)

0    1
1    3
2    5
3    7
dtype: int64

In [ ]:
print(s4)

0    ac
1    bd
dtype: object

In [ ]:
s5=Series(['a','b'])*3

In [ ]:
print(s5)

0    aaa
1    bbb
dtype: object

In [ ]:
import pandas as pd
data=pd.read_csv('/content/sample_data/california_housing_train.csv')
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
idx=data.columns
print(idx)
idx1=data.index
print(idx1)

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')
RangeIndex(start=0, stop=17000, step=1)

In [ ]:
#some index attributes
b=idx.is_monotonic_decreasing
print(b)
c=idx.is_monotonic_increasing
print(c)
e=idx.has_duplicates
print(e)
i=idx.nlevels
print(i)

False
False
False
1

In [ ]:
#Some index Methods

In [ ]:
A=idx.values #get as numpy array
print(A)
l=idx.tolist() #get as list
print(l)
# idx=idx.astype(int)#change datatype
# print(idx)

['longitude' 'latitude' 'housing_median_age' 'total_rooms'
 'total_bedrooms' 'population' 'households' 'median_income'
 'median_house_value']
['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value']

In [ ]:
b=idx.equals(0) #check for equality
print(b)

False

In [ ]:
idx=idx.union(idx1) #union of two index

In [ ]:
i=idx.nunique()#number unique labels
print(i)
label=idx.min() #minimumm label
print(label)
label=idx.max()
print(label)

9
households
total_rooms

In [ ]:
#From inline CSV text to a DataFrame
from io import StringIO
data = """, Animal, Cuteness, Desirable
row-1, dog, 8.7, True
row-2, cat, 9.5, True
row-3, bat, 2.6, False"""
df = pd.read_csv(StringIO(data), header=0,
 index_col=0, skipinitialspace=True)
# """ .....""" its docstring to keep multiple line in one line
print(df)

      Animal  Cuteness  Desirable
row-1    dog       8.7       True
row-2    cat       9.5       True
row-3    bat       2.6      False

In [ ]:
# Each Excel sheet in a Python dictionary
workbook = pd.ExcelFile('pandas.xlsx')
d = {} # start with an empty dictionary
for sheet_name in workbook.sheet_names:
 df = workbook.parse(sheet_name)
 d[sheet_name] = df

print(d)

In [ ]:
#Data in series then combine into a dataframe
s1=Series({'Tom':1,'Dick':2,'Har':3})
s2=Series({'Tom':3,'Dick':2,'Har':1})
s4=pd.concat({'A':s3,'B':s4},axis=0)
print(s1.index)
print(s1.values)
print(s4)

Index(['Tom', 'Dick', 'Har'], dtype='object')
[1 2 3]
A  0     c
   1     d
B  0    ac
   1    bd
dtype: object

In [ ]:
import pandas as pd
data=pd.read_csv('/content/sample_data/california_housing_train.csv')
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
n=4
dfh=data.head(n)
dfh

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0

In [ ]:
dft=data.tail(n)
dft

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
dfs=data.describe()
dfs

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
top_left_count_df=data.iloc[:5,:5]
#will show 5 rows and 5 columns
top_left_count_df

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms
0    -114.31     34.19                15.0       5612.0          1283.0
1    -114.47     34.40                19.0       7650.0          1901.0
2    -114.56     33.69                17.0        720.0           174.0
3    -114.57     33.64                14.0       1501.0           337.0
4    -114.57     33.57                20.0       1454.0           326.0

In [ ]:
data.ndim

2

In [ ]:
data.shape

(17000, 9)

In [ ]:
dft=data.T #transpose rows and cols
dft

,0,1,2,3,4,5,6,7,8,9,...,16990,16991,16992,16993,16994,16995,16996,16997,16998,16999
longitude,-114.3100,-114.47,-114.5600,-114.5700,-114.570,-114.5800,-114.5800,-114.5900,-114.5900,-114.6000,...,-124.2200,-124.2300,-124.2300,-124.2300,-124.2500,-124.2600,-124.2700,-124.3000,-124.3000,-124.3500
latitude,34.1900,34.40,33.6900,33.6400,33.570,33.6300,33.6100,34.8300,33.6100,34.8300,...,41.7300,41.7500,40.8100,40.5400,40.2800,40.5800,40.6900,41.8400,41.8000,40.5400
housing_median_age,15.0000,19.00,17.0000,14.0000,20.000,29.0000,25.0000,41.0000,34.0000,46.0000,...,28.0000,11.0000,52.0000,52.0000,32.0000,52.0000,36.0000,17.0000,19.0000,52.0000
total_rooms,5612.0000,7650.00,720.0000,1501.0000,1454.000,1387.0000,2907.0000,812.0000,4789.0000,1497.0000,...,3003.0000,3159.0000,1112.0000,2694.0000,1430.0000,2217.0000,2349.0000,2677.0000,2672.0000,1820.0000
total_bedrooms,1283.0000,1901.00,174.0000,337.0000,326.000,236.0000,680.0000,168.0000,1175.0000,309.0000,...,699.0000,616.0000,209.0000,453.0000,419.0000,394.0000,528.0000,531.0000,552.0000,300.0000
population,1015.0000,1129.00,333.0000,515.0000,624.000,671.0000,1841.0000,375.0000,3134.0000,787.0000,...,1530.0000,1343.0000,544.0000,1152.0000,434.0000,907.0000,1194.0000,1244.0000,1298.0000,806.0000
households,472.0000,463.00,117.0000,226.0000,262.000,239.0000,633.0000,158.0000,1056.0000,271.0000,...,653.0000,479.0000,172.0000,435.0000,187.0000,369.0000,465.0000,456.0000,478.0000,270.0000
median_income,1.4936,1.82,1.6509,3.1917,1.925,3.3438,2.6768,1.7083,2.1782,2.1908,...,1.7038,2.4805,3.3462,3.0806,1.9417,2.3571,2.5179,3.0313,1.9797,3.0147
median_house_value,66900.0000,80100.00,85700.0000,73400.0000,65500.000,74000.0000,82400.0000,48500.0000,58400.0000,48100.0000,...,78300.0000,73200.0000,50800.0000,106700.0000,76100.0000,111400.0000,79000.0000,103600.0000,85800.0000,94600.0000

In [ ]:
l=data.axes #list rows adn col indexs
l

[RangeIndex(start=0, stop=17000, step=1),
 Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
        'total_bedrooms', 'population', 'households', 'median_income',
        'median_house_value'],
       dtype='object')]

In [ ]:
(r,c)=data.axes # from above
r
print(c)

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
s=data.dtypes #Series column data types
s

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
type(data.values)

numpy.ndarray

In [ ]:
#dataframe utility methods
dfc=data.copy() #copy a dataframe
dfc

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
dfr=data.rank() #rank each row (default)
dfr

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,17000.0,8063.0,2517.5,15885.0,16149.0,6878.5,10223.0,655.0,888.5
1,16999.0,8855.0,4620.5,16493.0,16732.5,8065.0,10004.5,1463.0,1600.0
2,16998.0,1974.5,3648.5,1041.5,1292.0,792.0,774.5,981.5,1918.5
3,16996.5,1766.5,2136.0,4524.5,5517.0,1711.0,2580.0,7053.5,1302.0
4,16996.5,1591.0,5018.0,4209.0,5180.0,2552.0,3604.5,1744.5,817.5
...,...,...,...,...,...,...,...,...,...
16995,5.0,16802.0,16474.5,8970.5,7308.0,5642.5,7237.5,3416.0,3649.0
16996,4.0,16843.5,12167.0,9668.0,10761.5,8782.5,10059.0,4023.0,1557.0
16997,2.5,16994.0,3648.5,11142.5,10812.0,9266.0,9831.0,6242.5,3192.5
16998,2.5,16989.5,4620.5,11119.5,11209.0,9761.0,10361.0,1936.5,1927.5
16999,1.0,16771.0,16474.5,6652.0,4347.0,4444.0,3871.5,6142.0,2579.5

In [ ]:
dfs=data['longitude'].sort_values() #sort each col(default)
dfs
dfc=data.astype('string') #type conversion
dfc

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.4,19.0,7650.0,1901.0,1129.0,463.0,1.82,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.925,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.3,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.3,41.8,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
#Saving a Dataframe to a csv file
data.to_csv('name.csv')

In [ ]:
from pandas import ExcelWriter
writer=ExcelWriter('pandas1.xlsx')
data.to_excel(writer,'Sheet1')
data.to_excel(writer,'Sheet2')
writer.close()

In [ ]:
#Get column index and labels
idx=data.columns # get col index
print(idx)
label=data.columns[0] #1st col index
print(label)
lst=data.columns.tolist()#get as a list
print(lst)

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')
longitude
['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value']

In [ ]:
#Change column labels
data.rename(columns={'old':'new'},inplace=True)
data=data.rename(columns={'a':1,'b':'x'})
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
#Selecting Columns
s=data['longitude'] #Select col to Series
print(s)
s1=data[['longitude']] #Select col to df
print(s1)

0       -114.31
1       -114.47
2       -114.56
3       -114.57
4       -114.57
          ...
16995   -124.26
16996   -124.27
16997   -124.30
16998   -124.30
16999   -124.35
Name: longitude, Length: 17000, dtype: float64
       longitude
0        -114.31
1        -114.47
2        -114.56
3        -114.57
4        -114.57
...          ...
16995    -124.26
16996    -124.27
16997    -124.30
16998    -124.30
16999    -124.35

[17000 rows x 1 columns]

In [ ]:
#Selecting columns with python attributes
s=data.latitude
print(s)

0        34.19
1        34.40
2        33.69
3        33.64
4        33.57
         ...
16995    40.58
16996    40.69
16997    41.84
16998    41.80
16999    40.54
Name: latitude, Length: 17000, dtype: float64

In [ ]:
#cannot create new columns by attribute
data.population=data.latitude/data.longitude
print(data)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
0       -0.299099       472.0         1.4936             66900.0
1       -0.300515       463.0         1.8200             80100.0
2       -0.294082       117.0         1.6509             85700.0
3       -0.293620       226.0         3.1917             73400.0
4       -0.293009       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995   -0.326573       369.0         2.3571            111400.0
16996   -0.327432       465.0         2.5179             79000.0
16997   -0.336605       456.0         3.0313            103600.0
16998   -0.336283       478.0         1.9797             85800.0
16999   -0.326015       270.0         3.0147             94600.0

[17000 rows x 9 columns]

In [ ]:
#Adding new columns to a Dataframe
data['new_column1']=data.latitude/data.longitude
# data['new_column']=range(len(data))
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_column1
0,-114.31,34.19,15.0,5612.0,1283.0,-0.299099,472.0,1.4936,66900.0,-0.299099
1,-114.47,34.40,19.0,7650.0,1901.0,-0.300515,463.0,1.8200,80100.0,-0.300515
2,-114.56,33.69,17.0,720.0,174.0,-0.294082,117.0,1.6509,85700.0,-0.294082
3,-114.57,33.64,14.0,1501.0,337.0,-0.293620,226.0,3.1917,73400.0,-0.293620
4,-114.57,33.57,20.0,1454.0,326.0,-0.293009,262.0,1.9250,65500.0,-0.293009
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,-0.326573,369.0,2.3571,111400.0,-0.326573
16996,-124.27,40.69,36.0,2349.0,528.0,-0.327432,465.0,2.5179,79000.0,-0.327432
16997,-124.30,41.84,17.0,2677.0,531.0,-0.336605,456.0,3.0313,103600.0,-0.336605
16998,-124.30,41.80,19.0,2672.0,552.0,-0.336283,478.0,1.9797,85800.0,-0.336283
16999,-124.35,40.54,52.0,1820.0,300.0,-0.326015,270.0,3.0147,94600.0,-0.326015

In [ ]:
# Assuming 'data' is your DataFrame
data = data[['longitude', 'latitude'] + [col for col in data.columns if col not in ['longitude', 'latitude']]]
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_column1
0,-114.31,34.19,15.0,5612.0,1283.0,-0.299099,472.0,1.4936,66900.0,-0.299099
1,-114.47,34.40,19.0,7650.0,1901.0,-0.300515,463.0,1.8200,80100.0,-0.300515
2,-114.56,33.69,17.0,720.0,174.0,-0.294082,117.0,1.6509,85700.0,-0.294082
3,-114.57,33.64,14.0,1501.0,337.0,-0.293620,226.0,3.1917,73400.0,-0.293620
4,-114.57,33.57,20.0,1454.0,326.0,-0.293009,262.0,1.9250,65500.0,-0.293009
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,-0.326573,369.0,2.3571,111400.0,-0.326573
16996,-124.27,40.69,36.0,2349.0,528.0,-0.327432,465.0,2.5179,79000.0,-0.327432
16997,-124.30,41.84,17.0,2677.0,531.0,-0.336605,456.0,3.0313,103600.0,-0.336605
16998,-124.30,41.80,19.0,2672.0,552.0,-0.336283,478.0,1.9797,85800.0,-0.336283
16999,-124.35,40.54,52.0,1820.0,300.0,-0.326015,270.0,3.0147,94600.0,-0.326015

In [ ]:
#Droping Columns
data=data.drop('longitude',axis=1,inplace=True)
data